stages:
  - clone
  - install
  - build
  - deploy

variables:
  DOCKER_IMAGE: "your-dockerhub-username/laravel-burger-app"
  DOCKER_TAG: "latest"

clone_repo:
  stage: clone
  script:
    - echo "Cloning repository from GitHub..."
    - git clone https://github.com/your-github-username/your-repo-name.git -b DIABY_AbdoulJalil_Burger .
  only:
    - main

install_dependencies:
  stage: install
  script:
    - echo "Installing Laravel dependencies..."
    - composer install --prefer-dist --no-progress --no-suggest
  only:
    - main

build_docker_image:
  stage: build
  script:
    - echo "Building Docker image..."
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    # Ajoutez ici les commandes pour déployer votre application (par exemple, sur un serveur ou un cluster Kubernetes)
  only:
    - main
