version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: isi-burger:latest
        container_name: isi-burger_app
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www
        depends_on:
            - db
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=isi_burger
            - DB_USERNAME=postgres
            - DB_PASSWORD=passer

    db:
        image: postgres:latest
        container_name: isi-burger_db
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: isi_burger
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: passer
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
